[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules package-lock.json && npm install && npm run build"

[deploy]
startCommand = "npx serve dist -s -l $PORT"

[build.env]
NIXPACKS_NODE_VERSION = "20"
